services:
  strapi:
    image: cmspatas-strapi
    container_name: cmspatas_strapi
    expose:
      - "1337"
    restart: always
    networks:
      - cmspatas_net

  nginx:
    image: nginx:latest
    container_name: cmspatas_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/cms.metidasdepata.com.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
    depends_on:
      - strapi
    networks:
      - cmspatas_net

  certbot:
    image: certbot/certbot
    container_name: cmspatas_certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: >
      /bin/sh -c "trap exit TERM;
      while :; do
        certbot renew;
        sleep 12h;
      done"
    networks:
      - cmspatas_net

volumes:
  certbot-etc:
  certbot-var:

networks:
  cmspatas_net:
