
services:
  strapi:
    build: .
    container_name: cmspatas_strapi
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:1337:1337"
    depends_on:
      - db
    volumes:
      - ./public/uploads:/app/public/uploads

  db:
    image: postgres:16-alpine
    container_name: cmspatas_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    container_name: cmspatas_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/cms.metidasdepata.com.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/share/nginx/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - strapi

  certbot:
    image: certbot/certbot
    container_name: cmspatas_certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./public:/usr/share/nginx/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done'"
volumes:
  pgdata:
  certbot-etc:
  certbot-var:
